### ISSUE TITLE
Axis labels missing

### ISSUE THREAD

**Issue by renepickhardt** [ajtowns/discourse-plotly-theme-component#1]
Not sure if you just didn't provide the API in your readme or if it is not a available. But also in your delving post there are labels to the x and y axis missing. I am sure plotly supports this. It would be great if you could either expose this or add to your readme how to use it if already exposed

**Comment by ajtowns** [comment]
Whoops, added examples on the delving post, namely:

```
layout:
  title: Feerate Diagram
  xaxis:
    title: "size"
  yaxis:
    title: "fees"
```

cf https://plotly.com/javascript/line-charts/#colored-and-styled-scatter-plot
